language: php

php: 7.2

branches:
    only:
        - master

cache:
  directories:
    - $HOME/.composer/cache

install:
    - composer install

before_script:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

script:
    - composer check-cs
    - composer phpstan
    - composer tests
